// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleUnitTesting.Infrastructure;

#nullable disable

namespace SampleUnitTesting.Infrastructure.Configuration.Migrations
{
    [DbContext(typeof(SampleUnitTestingDbContext))]
    [Migration("20220508045857_DropCustomerAttendantsTable")]
    partial class DropCustomerAttendantsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AttendantCustomer", b =>
                {
                    b.Property<int>("AttendantsId")
                        .HasColumnType("int");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.HasKey("AttendantsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("AttendantCustomer", "SampleUnitTesting");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.Attendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 58, 57, 52, DateTimeKind.Utc).AddTicks(6800));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 58, 57, 52, DateTimeKind.Utc).AddTicks(6929));

                    b.HasKey("Id");

                    b.ToTable("Attendants", "SampleUnitTesting");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 58, 57, 52, DateTimeKind.Utc).AddTicks(7620));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 58, 57, 52, DateTimeKind.Utc).AddTicks(7779));

                    b.HasKey("Id");

                    b.ToTable("Customers", "SampleUnitTesting");
                });

            modelBuilder.Entity("AttendantCustomer", b =>
                {
                    b.HasOne("SampleUnitTesting.Domain.Attendant", null)
                        .WithMany()
                        .HasForeignKey("AttendantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleUnitTesting.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
