// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleUnitTesting.Infrastructure;

#nullable disable

namespace SampleUnitTesting.Infrastructure.Configuration.Migrations
{
    [DbContext(typeof(SampleUnitTestingDbContext))]
    [Migration("20220508040220_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SampleUnitTesting.Domain.Attendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 2, 20, 755, DateTimeKind.Utc).AddTicks(6071));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 2, 20, 755, DateTimeKind.Utc).AddTicks(6196));

                    b.HasKey("Id");

                    b.ToTable("Attendants", "SampleUnitTesting");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 2, 20, 755, DateTimeKind.Utc).AddTicks(6885));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 5, 8, 4, 2, 20, 755, DateTimeKind.Utc).AddTicks(7008));

                    b.HasKey("Id");

                    b.ToTable("Customers", "SampleUnitTesting");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.CustomerAttendant", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("AttendantId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "AttendantId");

                    b.HasIndex("AttendantId");

                    b.ToTable("CustomerAttendants", "SampleUnitTesting");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.CustomerAttendant", b =>
                {
                    b.HasOne("SampleUnitTesting.Domain.Attendant", "Attendant")
                        .WithMany("Customers")
                        .HasForeignKey("AttendantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleUnitTesting.Domain.Customer", "Customer")
                        .WithMany("Attendants")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendant");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.Attendant", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("SampleUnitTesting.Domain.Customer", b =>
                {
                    b.Navigation("Attendants");
                });
#pragma warning restore 612, 618
        }
    }
}
